### ISSUE TITLE
Question: How does one pass styling for the elements in this plugin?

### ISSUE THREAD

**Issue by seigel** [inkdropapp/inkdrop-flowchart#1]
According to the webpage for flowchart.js, one can style the elements and the connecting edges.  Just wondering if you had an example of coloring the ```condition``` for example?
Thanks

**Comment by craftzdog** [comment]
Hi,

This example code works fine:

```
st=>start: Improve your
l10n process!
e=>end: Continue to have fun!:>https://youtu.be/YQryHo1iHb8[blank]
op1=>operation: Go to locize.com:>https://locize.com[blank]
sub1=>subroutine: Read the awesomeness
cond(align-next=no)=>condition: Interested to
getting started?
io=>inputoutput: Register:>https://www.locize.io/register[blank]
sub2=>subroutine: Read about improving
your localization workflow
or another source:>https://medium.com/@adrai/8-signs-you-should-improve-your-localization-process-3dc075d53998[blank]
op2=>operation: Login:>https://www.locize.io/login[blank]
cond2=>condition: valid password?
cond3=>condition: reset password?
op3=>operation: send email
sub3=>subroutine: Create a demo project
sub4=>subroutine: Start your real project
io2=>inputoutput: Subscribe

st->op1->sub1->cond
cond(yes)->io->op2->cond2
cond2(no)->cond3
cond3(no,bottom)->op2
cond3(yes)->op3
op3(right)->op2
cond2(yes)->sub3
sub3->sub4->io2->e
cond(no)->sub2(right)->op1

st@>op1({"stroke":"Red"})@>sub1({"stroke":"Red"})@>cond({"stroke":"Red"})@>io({"stroke":"Red"})@>op2({"stroke":"Red"})@>cond2({"stroke":"Red"})@>sub3({"stroke":"Red"})@>sub4({"stroke":"Red"})@>io2({"stroke":"Red"})@>e({"stroke":"Red","stroke-width":6,"arrow-end":"classic-wide-long"})
```

<img width="1440" alt="Screen Shot 2019-06-06 at 20 20 31" src="https://user-images.githubusercontent.com/1332805/59029193-9a800b00-8898-11e9-9346-2006b89aa13d.png">

But seems like it does not support changing colors of `condition` from a flowchart codeblock without using JS:

https://github.com/adrai/flowchart.js/issues/21

**Comment by seigel** [comment]
I was thinking, for example, about making the background of the condition red.  On flowchart.js it would appear that one has to set up some flowstate stuff.  I was wondering if there is some sneaky inline way of accomplishing the same feat.

**Comment by craftzdog** [comment]
Is this not an answer to your question?

> But seems like it does not support changing colors of `condition` from a flowchart codeblock without using JS:
> 
> https://github.com/adrai/flowchart.js/issues/21

**Comment by seigel** [comment]
You are right. That does answer the question, one can’t.  Oh well. :). Sorry to waste your time.

**Comment by craftzdog** [comment]
You're welcome! Closing this.
